/** @generated by @calimero/abi-codegen — DO NOT EDIT. */
/* eslint-disable @typescript-eslint/no-unused-vars */

import {
  MeroJs,
} from '@calimero-network/mero-react';

// Generated types

export interface Event_MatchCreated {
  id: string;
}

export interface Event_MatchIdCollision {
  attempted_id: string;
}

export interface LobbyState {
  created_ms: number;
  matches: Record<string, MatchSummary>;
  player_stats: Record<string, PlayerStats>;
  history: MatchRecord[];
}

export interface MatchRecord {
  match_id: string;
  winner: string;
  loser: string;
  finished_ms: number;
}

export type MatchStatus =
  | 'Pending'
  | 'Active'
  | 'Finished';

export interface MatchSummary {
  match_id: string;
  player1: string;
  player2: string;
  status: MatchStatus;
  context_id: string | null;
  winner: string | null;
  created_ms: number;
}

export interface PlayerStats {
  wins: {  };
  losses: {  };
  games_played: {  };
}

export interface PlayerStatsView {
  wins: number;
  losses: number;
  games_played: number;
}





export type AbiEvent =
  | { name: "MatchCreated"; payload: Event_MatchCreated }
  | { name: "MatchIdCollision"; payload: Event_MatchIdCollision }
  | { name: "MatchListUpdated" }
  | { name: "PlayerStatsUpdated" }
;


/**
 * Utility class for handling byte conversions in Calimero
 */
export class CalimeroBytes {
  private data: Uint8Array;

  constructor(input: string | number[] | Uint8Array) {
    if (typeof input === "string") {
      // Hex string
      this.data = new Uint8Array(
        input.match(/.{1,2}/g)?.map((byte) => parseInt(byte, 16)) || []
      );
    } else if (Array.isArray(input)) {
      // Number array
      this.data = new Uint8Array(input);
    } else {
      // Uint8Array
      this.data = input;
    }
  }

  toArray(): number[] {
    return Array.from(this.data);
  }

  toUint8Array(): Uint8Array {
    return this.data;
  }

  static fromHex(hex: string): CalimeroBytes {
    return new CalimeroBytes(hex);
  }

  static fromArray(arr: number[]): CalimeroBytes {
    return new CalimeroBytes(arr);
  }

  static fromUint8Array(bytes: Uint8Array): CalimeroBytes {
    return new CalimeroBytes(bytes);
  }
}

/**
 * Convert CalimeroBytes instances to arrays for WASM compatibility
 */
function convertCalimeroBytesForWasm(obj: any): any {
  if (obj === null || obj === undefined) {
    return obj;
  }

  if (obj instanceof CalimeroBytes) {
    return obj.toArray();
  }

  if (Array.isArray(obj)) {
    return obj.map(item => convertCalimeroBytesForWasm(item));
  }

  if (typeof obj === "object") {
    const result: any = {};
    for (const [key, value] of Object.entries(obj)) {
      result[key] = convertCalimeroBytesForWasm(value);
    }
    return result;
  }

  return obj;
}

/**
 * Convert arrays back to CalimeroBytes instances from WASM responses
 */
function convertWasmResultToCalimeroBytes(obj: any): any {
  if (obj === null || obj === undefined) {
    return obj;
  }

  if (Array.isArray(obj) && obj.every(item => typeof item === "number")) {
    return new CalimeroBytes(obj);
  }

  if (Array.isArray(obj)) {
    return obj.map(item => convertWasmResultToCalimeroBytes(item));
  }

  if (typeof obj === "object") {
    const result: any = {};
    for (const [key, value] of Object.entries(obj)) {
      result[key] = convertWasmResultToCalimeroBytes(value);
    }
    return result;
  }

  return obj;
}

export class LobbyClient {
  private mero: MeroJs;
  private contextId: string;
  private executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this.mero = mero;
    this.contextId = contextId;
    this.executorPublicKey = executorPublicKey;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    const response = await this.mero.rpc.execute({ contextId: this.contextId, method: 'init', argsJson: {}, executorPublicKey: this.executorPublicKey });
    return response as void;
  }

  /**
   * create_match
   */
  public async createMatch(params: { player2: string }): Promise<string> {
    const response = await this.mero.rpc.execute({ contextId: this.contextId, method: 'create_match', argsJson: params, executorPublicKey: this.executorPublicKey });
    return response as string;
  }

  /**
   * set_match_context_id
   */
  public async setMatchContextId(params: { match_id: string; context_id: string }): Promise<void> {
    const response = await this.mero.rpc.execute({ contextId: this.contextId, method: 'set_match_context_id', argsJson: params, executorPublicKey: this.executorPublicKey });
    return response as void;
  }

  /**
   * get_matches
   */
  public async getMatches(): Promise<MatchSummary[]> {
    const response = await this.mero.rpc.execute({ contextId: this.contextId, method: 'get_matches', argsJson: {}, executorPublicKey: this.executorPublicKey });
    return response as MatchSummary[];
  }

  /**
   * get_player_stats
   */
  public async getPlayerStats(params: { player: string }): Promise<PlayerStatsView> {
    const response = await this.mero.rpc.execute({ contextId: this.contextId, method: 'get_player_stats', argsJson: params, executorPublicKey: this.executorPublicKey });
    return response as PlayerStatsView;
  }

  /**
   * get_history
   */
  public async getHistory(): Promise<MatchRecord[]> {
    const response = await this.mero.rpc.execute({ contextId: this.contextId, method: 'get_history', argsJson: {}, executorPublicKey: this.executorPublicKey });
    return response as MatchRecord[];
  }

  /**
   * on_match_finished
   */
  public async onMatchFinished(params: { match_id: string; winner: string; loser: string }): Promise<void> {
    const response = await this.mero.rpc.execute({ contextId: this.contextId, method: 'on_match_finished', argsJson: params, executorPublicKey: this.executorPublicKey });
    return response as void;
  }

}