/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import {
  MeroJs,
} from '@calimero-network/mero-react';

// Generated types

export interface Event_MatchCreated {
  id: string;
}

export interface Event_MatchIdCollision {
  attempted_id: string;
}

export interface LobbyState {
  created_ms: number;
  matches: Record<string, MatchSummary>;
  player_stats: Record<string, PlayerStats>;
  history: MatchRecord[];
}

export interface MatchRecord {
  match_id: string;
  winner: string;
  loser: string;
  finished_ms: number;
}

export type MatchStatus = 'Pending' | 'Active' | 'Finished';

export interface MatchSummary {
  match_id: string;
  player1: string;
  player2: string;
  status: MatchStatus;
  context_id: string | null;
  winner: string | null;
  created_ms: number;
}

export interface PlayerStats {
  wins: {  };
  losses: {  };
  games_played: {  };
}

export interface PlayerStatsView {
  wins: number;
  losses: number;
  games_played: number;
}





export type AbiEvent =
  | { name: "MatchCreated"; payload: Event_MatchCreated }
  | { name: "MatchIdCollision"; payload: Event_MatchIdCollision }
  | { name: "MatchListUpdated" }
  | { name: "PlayerStatsUpdated" }
;


export class LobbyClient {
  private _mero: MeroJs;
  private _contextId: string;
  private _executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this._mero = mero;
    this._contextId = contextId;
    this._executorPublicKey = executorPublicKey;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'init', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * create_match
   */
  public async createMatch(params: { player2: string }): Promise<string> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'create_match', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as string;
  }

  /**
   * set_match_context_id
   */
  public async setMatchContextId(params: { match_id: string; context_id: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'set_match_context_id', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

  /**
   * get_matches
   */
  public async getMatches(): Promise<MatchSummary[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_matches', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as MatchSummary[];
  }

  /**
   * get_player_stats
   */
  public async getPlayerStats(params: { player: string }): Promise<PlayerStatsView> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_player_stats', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as PlayerStatsView;
  }

  /**
   * get_history
   */
  public async getHistory(): Promise<MatchRecord[]> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'get_history', argsJson: {}, executorPublicKey: this._executorPublicKey });
    return response as MatchRecord[];
  }

  /**
   * on_match_finished
   */
  public async onMatchFinished(params: { match_id: string; winner: string; loser: string }): Promise<void> {
    const response = await this._mero.rpc.execute({ contextId: this._contextId, method: 'on_match_finished', argsJson: params, executorPublicKey: this._executorPublicKey });
    return response as void;
  }

}