/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import {
  MeroJs,
} from '@calimero-network/mero-react';

// Generated types

export interface OwnBoardView {
  size: number;
  board: CalimeroBytes;
}

export interface ShotsView {
  size: number;
  shots: CalimeroBytes;
}

export type MatchStatus = 'Pending' | 'Active' | 'Finished';

export interface MatchSummary {
  match_id: string;
  player1: string;
  player2: string;
  status: MatchStatus;
  context_id: string | null;
  winner: string | null;
}


/**
 * Utility class for handling byte conversions in Calimero
 */
export class CalimeroBytes {
  private data: Uint8Array;

  constructor(input: string | number[] | Uint8Array) {
    if (typeof input === "string") {
      // Hex string
      this.data = new Uint8Array(
        input.match(/.{1,2}/g)?.map((byte) => parseInt(byte, 16)) || []
      );
    } else if (Array.isArray(input)) {
      // Number array
      this.data = new Uint8Array(input);
    } else {
      // Uint8Array
      this.data = input;
    }
  }

  toArray(): number[] {
    return Array.from(this.data);
  }

  toUint8Array(): Uint8Array {
    return this.data;
  }

  static fromHex(hex: string): CalimeroBytes {
    return new CalimeroBytes(hex);
  }

  static fromArray(arr: number[]): CalimeroBytes {
    return new CalimeroBytes(arr);
  }

  static fromUint8Array(bytes: Uint8Array): CalimeroBytes {
    return new CalimeroBytes(bytes);
  }
}

/**
 * Convert CalimeroBytes instances to arrays for WASM compatibility
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function convertCalimeroBytesForWasm(obj: any): any {
  if (obj === null || obj === undefined) {
    return obj;
  }

  if (obj instanceof CalimeroBytes) {
    return obj.toArray();
  }

  if (Array.isArray(obj)) {
    return obj.map(item => convertCalimeroBytesForWasm(item));
  }

  if (typeof obj === "object") {
    const result: any = {};
    for (const [key, value] of Object.entries(obj)) {
      result[key] = convertCalimeroBytesForWasm(value);
    }
    return result;
  }

  return obj;
}

/**
 * Convert arrays back to CalimeroBytes instances from WASM responses
 */
function convertWasmResultToCalimeroBytes(obj: any): any {
  if (obj === null || obj === undefined) {
    return obj;
  }

  if (Array.isArray(obj) && obj.every(item => typeof item === "number")) {
    return new CalimeroBytes(obj);
  }

  if (Array.isArray(obj)) {
    return obj.map(item => convertWasmResultToCalimeroBytes(item));
  }

  if (typeof obj === "object") {
    const result: any = {};
    for (const [key, value] of Object.entries(obj)) {
      result[key] = convertWasmResultToCalimeroBytes(value);
    }
    return result;
  }

  return obj;
}

export class AbiClient {
  private mero: MeroJs;
  private contextId: string;
  private executorPublicKey: string;

  constructor(mero: MeroJs, contextId: string, executorPublicKey: string) {
    this.mero = mero;
    this.contextId = contextId;
    this.executorPublicKey = executorPublicKey;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    const response = await this.mero.rpc.execute({ contextId: this.contextId, method: 'init', argsJson: {}, executorPublicKey: this.executorPublicKey });
    return response as void;
  }

  /**
   * create_match
   */
  public async createMatch(params: { player2: string }): Promise<string> {
    const response = await this.mero.rpc.execute({ contextId: this.contextId, method: 'create_match', argsJson: params, executorPublicKey: this.executorPublicKey });
    return response as string;
  }

  /**
   * place_ships
   */
  public async placeShips(params: { match_id: string; ships: string[] }): Promise<void> {
    const response = await this.mero.rpc.execute({ contextId: this.contextId, method: 'place_ships', argsJson: params, executorPublicKey: this.executorPublicKey });
    return response as void;
  }

  /**
   * propose_shot
   */
  public async proposeShot(params: { match_id: string; x: number; y: number }): Promise<void> {
    const response = await this.mero.rpc.execute({ contextId: this.contextId, method: 'propose_shot', argsJson: params, executorPublicKey: this.executorPublicKey });
    return response as void;
  }

  /**
   * acknowledge_shot
   */
  public async acknowledgeShot(params: { match_id: string }): Promise<string> {
    const response = await this.mero.rpc.execute({ contextId: this.contextId, method: 'acknowledge_shot', argsJson: params, executorPublicKey: this.executorPublicKey });
    return response as string;
  }

  /**
   * get_own_board
   */
  public async getOwnBoard(params: { match_id: string }): Promise<OwnBoardView> {
    const response = await this.mero.rpc.execute({ contextId: this.contextId, method: 'get_own_board', argsJson: params, executorPublicKey: this.executorPublicKey });
    return convertWasmResultToCalimeroBytes(response) as OwnBoardView;
  }

  /**
   * get_shots
   */
  public async getShots(params: { match_id: string }): Promise<ShotsView> {
    const response = await this.mero.rpc.execute({ contextId: this.contextId, method: 'get_shots', argsJson: params, executorPublicKey: this.executorPublicKey });
    return convertWasmResultToCalimeroBytes(response) as ShotsView;
  }

  /**
   * get_matches
   */
  public async getMatches(): Promise<MatchSummary[]> {
    const response = await this.mero.rpc.execute({ contextId: this.contextId, method: 'get_matches', argsJson: {}, executorPublicKey: this.executorPublicKey });
    return response as MatchSummary[];
  }

  /**
   * set_match_context_id
   */
  public async setMatchContextId(params: { match_id: string; context_id: string }): Promise<void> {
    const response = await this.mero.rpc.execute({ contextId: this.contextId, method: 'set_match_context_id', argsJson: params, executorPublicKey: this.executorPublicKey });
    return response as void;
  }

  /**
   * get_active_match_id
   */
  public async getActiveMatchId(): Promise<string> {
    const response = await this.mero.rpc.execute({ contextId: this.contextId, method: 'get_active_match_id', argsJson: {}, executorPublicKey: this.executorPublicKey });
    return response as string;
  }

  /**
   * get_current_turn
   */
  public async getCurrentTurn(): Promise<string> {
    const response = await this.mero.rpc.execute({ contextId: this.contextId, method: 'get_current_turn', argsJson: {}, executorPublicKey: this.executorPublicKey });
    return response as string;
  }

  /**
   * get_current_user
   */
  public async getCurrentUser(): Promise<string> {
    const response = await this.mero.rpc.execute({ contextId: this.contextId, method: 'get_current_user', argsJson: {}, executorPublicKey: this.executorPublicKey });
    return response as string;
  }

  /**
   * acknowledge_shot_handler
   */
  public async acknowledgeShotHandler(params: { id: string; x: number; y: number }): Promise<void> {
    const response = await this.mero.rpc.execute({ contextId: this.contextId, method: 'acknowledge_shot_handler', argsJson: params, executorPublicKey: this.executorPublicKey });
    return response as void;
  }

}