/** @generated by @calimero/abi-codegen — DO NOT EDIT. */

import { MeroJs, AppContext } from '@calimero-network/mero-react';

// Generated types

export interface OwnBoardView {
  size: number;
  board: CalimeroBytes;
}

export interface ShotsView {
  size: number;
  shots: CalimeroBytes;
}

/**
 * Utility class for handling byte conversions in Calimero
 */
export class CalimeroBytes {
  private data: Uint8Array;

  constructor(input: string | number[] | Uint8Array) {
    if (typeof input === 'string') {
      // Hex string
      this.data = new Uint8Array(
        input.match(/.{1,2}/g)?.map((byte) => parseInt(byte, 16)) || [],
      );
    } else if (Array.isArray(input)) {
      // Number array
      this.data = new Uint8Array(input);
    } else {
      // Uint8Array
      this.data = input;
    }
  }

  toArray(): number[] {
    return Array.from(this.data);
  }

  toUint8Array(): Uint8Array {
    return this.data;
  }

  static fromHex(hex: string): CalimeroBytes {
    return new CalimeroBytes(hex);
  }

  static fromArray(arr: number[]): CalimeroBytes {
    return new CalimeroBytes(arr);
  }

  static fromUint8Array(bytes: Uint8Array): CalimeroBytes {
    return new CalimeroBytes(bytes);
  }
}

/**
 * Convert CalimeroBytes instances to arrays for WASM compatibility
 */
function convertCalimeroBytesForWasm(obj: any): any {
  if (obj === null || obj === undefined) {
    return obj;
  }

  if (obj instanceof CalimeroBytes) {
    return obj.toArray();
  }

  if (Array.isArray(obj)) {
    return obj.map((item) => convertCalimeroBytesForWasm(item));
  }

  if (typeof obj === 'object') {
    const result: any = {};
    for (const [key, value] of Object.entries(obj)) {
      result[key] = convertCalimeroBytesForWasm(value);
    }
    return result;
  }

  return obj;
}

/**
 * Convert arrays back to CalimeroBytes instances from WASM responses
 */
function convertWasmResultToCalimeroBytes(obj: any): any {
  if (obj === null || obj === undefined) {
    return obj;
  }

  if (Array.isArray(obj) && obj.every((item) => typeof item === 'number')) {
    return new CalimeroBytes(obj);
  }

  if (Array.isArray(obj)) {
    return obj.map((item) => convertWasmResultToCalimeroBytes(item));
  }

  if (typeof obj === 'object') {
    const result: any = {};
    for (const [key, value] of Object.entries(obj)) {
      result[key] = convertWasmResultToCalimeroBytes(value);
    }
    return result;
  }

  return obj;
}

export class AbiClient {
  private app: MeroJs;
  private context: AppContext;

  constructor(app: MeroJs, context: AppContext) {
    this.app = app;
    this.context = context;
  }

  /**
   * init
   */
  public async init(): Promise<void> {
    const response = await this.app.rpc.execute({
      contextId: this.context.contextId,
      method: 'init',
      argsJson: '{}',
      executorPublicKey: this.context.executorId,
    });
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * create_match
   */
  public async createMatch(params: { player2: string }): Promise<string> {
    const response = await this.app.rpc.execute({
      contextId: this.context.contextId,
      method: 'create_match',
      argsJson: JSON.stringify(params),
      executorPublicKey: this.context.executorId,
    });
    if (response.success) {
      return response.result as string;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * place_ships
   */
  public async placeShips(params: {
    match_id: string;
    ships: string[];
  }): Promise<void> {
    const response = await this.app.rpc.execute({
      contextId: this.context.contextId,
      method: 'place_ships',
      argsJson: JSON.stringify(params),
      executorPublicKey: this.context.executorId,
    });
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * propose_shot
   */
  public async proposeShot(params: {
    match_id: string;
    x: number;
    y: number;
  }): Promise<void> {
    const response = await this.app.rpc.execute({
      contextId: this.context.contextId,
      method: 'propose_shot',
      argsJson: JSON.stringify(params),
      executorPublicKey: this.context.executorId,
    });
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * acknowledge_shot
   */
  public async acknowledgeShot(params: { match_id: string }): Promise<string> {
    const response = await this.app.rpc.execute({
      contextId: this.context.contextId,
      method: 'acknowledge_shot',
      argsJson: JSON.stringify(params),
      executorPublicKey: this.context.executorId,
    });
    if (response.success) {
      return response.result as string;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * get_own_board
   */
  public async getOwnBoard(params: {
    match_id: string;
  }): Promise<OwnBoardView> {
    const response = await this.app.rpc.execute({
      contextId: this.context.contextId,
      method: 'get_own_board',
      argsJson: JSON.stringify(params),
      executorPublicKey: this.context.executorId,
    });
    if (response.success) {
      return convertWasmResultToCalimeroBytes(response.result) as OwnBoardView;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * get_shots
   */
  public async getShots(params: { match_id: string }): Promise<ShotsView> {
    const response = await this.app.rpc.execute({
      contextId: this.context.contextId,
      method: 'get_shots',
      argsJson: JSON.stringify(params),
      executorPublicKey: this.context.executorId,
    });
    if (response.success) {
      return convertWasmResultToCalimeroBytes(response.result) as ShotsView;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * get_matches
   */
  public async getMatches(): Promise<string[]> {
    const response = await this.app.rpc.execute({
      contextId: this.context.contextId,
      method: 'get_matches',
      argsJson: '{}',
      executorPublicKey: this.context.executorId,
    });
    if (response.success) {
      return response.result as string[];
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * get_active_match_id
   */
  public async getActiveMatchId(): Promise<string> {
    const response = await this.app.rpc.execute({
      contextId: this.context.contextId,
      method: 'get_active_match_id',
      argsJson: '{}',
      executorPublicKey: this.context.executorId,
    });
    if (response.success) {
      return response.result as string;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * get_current_turn
   */
  public async getCurrentTurn(): Promise<string> {
    const response = await this.app.rpc.execute({
      contextId: this.context.contextId,
      method: 'get_current_turn',
      argsJson: '{}',
      executorPublicKey: this.context.executorId,
    });
    if (response.success) {
      return response.result as string;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * get_current_user
   */
  public async getCurrentUser(): Promise<string> {
    const response = await this.app.rpc.execute({
      contextId: this.context.contextId,
      method: 'get_current_user',
      argsJson: '{}',
      executorPublicKey: this.context.executorId,
    });
    if (response.success) {
      return response.result as string;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }

  /**
   * acknowledge_shot_handler
   */
  public async acknowledgeShotHandler(params: {
    id: string;
    x: number;
    y: number;
  }): Promise<void> {
    const response = await this.app.rpc.execute({
      contextId: this.context.contextId,
      method: 'acknowledge_shot_handler',
      argsJson: JSON.stringify(params),
      executorPublicKey: this.context.executorId,
    });
    if (response.success) {
      return response.result as void;
    } else {
      throw new Error(response.error || 'Execution failed');
    }
  }
}
